version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:12
    restart: unless-stopped
    environment:
      POSTGRES_DB: projectManagementSys
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ahmadyazdi243@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      POSTGRES_HOST: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: projectManagementSys
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data: